### ISSUE TITLE
uuid.UUID should be used for validating an uuid

### ISSUE THREAD

**Issue by udangel-r7** [logentries/le_lambda#1]
we should _NOT_ use a regex for validating an UUID

**Comment by omgapuppy** [comment]
@udangel-r7 the reasoning behind this was to keep it simple instead of making multiple calls. When creating a new token based log, UUID 3 token is created. When updating the log, creating a new token, UUID 4 token is returned (i.e the script doesn't know which version it's validating; the regex pattern matches uuid 1-5).

Do you think it's still better to write validation using uuid.UUID, even if it complicates the validation process by another step or two?

**Comment by omgapuppy** [comment]
sticking to regex as per [this discussion](http://stackoverflow.com/questions/11384589/what-is-the-correct-regex-for-matching-values-generated-by-uuid-uuid4-hex) and [this example.](http://pythonfiddle.com/create-uuid-object-with-wrong-uuid/) Current implementation doesn't affect performance or functionality in any way.
